### PR TITLE
Update Gradle and build dependencies

### PR DESCRIPTION
**Pull request by friederbluemle**
This updates Gradle wrapper to `4.2.1`, the build tools to `26.0.2`, and the Android Gradle plugin to `3.0.0-beta7`.

### CODE REVIEW

**Comment by jshvarts** [comment]
Hey, thanks for your contribution. How come binary files are included in this commit? 

Based on failing travis CI, I think this should be the diff:

```
$ git diff
diff --git a/.travis.yml b/.travis.yml
index 922fbe3..1c7da0a 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -8,7 +8,7 @@ android:
     - tools
 
     # The BuildTools version used by your project
-    - build-tools-25.0.2
+    - build-tools-26.0.2
 
diff --git a/app/build.gradle b/app/build.gradle
index 60bb7c8..5ae97e2 100644
--- a/app/build.gradle
+++ b/app/build.gradle
@@ -18,7 +18,6 @@ project.ext {
 
 android {
     compileSdkVersion 25
-    buildToolsVersion "25.0.2"
     defaultConfig {
         applicationId "com.example.offline"
         minSdkVersion 16
diff --git a/build.gradle b/build.gradle
index 39c0b9a..71f483a 100644
--- a/build.gradle
+++ b/build.gradle
@@ -3,7 +3,7 @@
 buildscript {
 
     ext {
-        androidGradlePluginVersion = '3.0.0-alpha5'
+        androidGradlePluginVersion = '3.0.0-beta7'
         roomVersion = '1.0.0-alpha4'
     }
 
diff --git a/gradle/wrapper/gradle-wrapper.properties b/gradle/wrapper/gradle-wrapper.properties
index 2095e49..c46adda 100644
--- a/gradle/wrapper/gradle-wrapper.properties
+++ b/gradle/wrapper/gradle-wrapper.properties
@@ -3,4 +3,4 @@ distributionBase=GRADLE_USER_HOME
 distributionPath=wrapper/dists
 zipStoreBase=GRADLE_USER_HOME
 zipStorePath=wrapper/dists
-distributionUrl=https\://services.gradle.org/distributions/gradle-4.1-milestone-1-all.zip
+distributionUrl=https\://services.gradle.org/distributions/gradle-4.2.1-all.zip
```

**Comment by friederbluemle** [comment]
@jshvarts Hey, thanks for the comment and sorry for not checking Travis CI earlier!

To answer your questions:
The Gradle wrapper was updated by invoking the standard task

    gradle wrapper --gradle-version 4.2.1 --distribution-type=all

This is why the build shell scripts were updated to the latest version as well. If you run this command locally, you will also notice that the binary `.jar` file will change every time you run the command (the reason is most likely that an internal timestamp keeps changing).

I amended the PR to include the update to build-tools `26.0.2` - Waiting for Travis to report back.
Thanks!!

**Comment by friederbluemle** [comment]
I added one more commit that replaces `compile` with `implementation`. It is the new way of declaring compile time dependencies. It was change with the new Android Gradle plugin and does the same exact thing.

It will get rid of this warning:

    Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.

**Comment by jshvarts** [comment]
Awesome, thanks for clarifyng about gradlew. 

Could you execute `./gradlew clean assembleDebug check` in the branch to perform lint, checkstyle, pmd, findbugs checks after these changes? I should really integrate this custom `clean` task as part of travis CI build or at least document contribution guidelines :)

**Comment by friederbluemle** [comment]
I did execute `./gradlew clean assembleDebug check` and everything passes without any errors.
I'm not sure what you mean by "this custom `clean` task". Did you mean `check`? It is easy to make Travis run the `check` task as well.

By default, Travis runs `./gradlew build connectedCheck`, I added another commit to make it run `./gradlew build check` instead (there are no tests for `connectedCheck` in this project anyway). I think it makes sense to also run `check` on Travis as well 👍

**Comment by friederbluemle** [comment]
D'oh, I just realized: `check` is already a *dependency* of `build` - meaning it was running on Travis all along! I removed the commit again. Sorry for the confusion ;)

**Comment by jshvarts** [comment]
I see! Sorry for the confusion--I did not know that check is already being executed for each build!

By custom `check` I meant that I bundled more steps to include in the check task in https://github.com/jshvarts/OfflineSampleApp/blob/master/config/quality.gradle:

```
// Add checkstyle, findbugs, pmd and lint to the check task.
check.dependsOn 'checkstyle', 'findbugs', 'pmd', 'lint'
```
Will merge now! Thanks :)

**Pull request merged**
